// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: tune_bar

#ifndef UI_SCREEN_BOOT_H
#define UI_SCREEN_BOOT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_Boot
extern void ui_Screen_Boot_screen_init(void);
extern void ui_Screen_Boot_screen_destroy(void);
extern void ui_event_Screen_Boot(lv_event_t * e);
extern lv_obj_t * ui_Screen_Boot;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

