// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: tune_bar

#include "../ui.h"
#include "../ui_helpers.h"

lv_obj_t * ui_Screen_Settings = NULL;
lv_obj_t * ui_MainMenu_Tabview_ConfigPanel = NULL;
lv_obj_t * ui_MainMenu_Tabpage_network = NULL;
lv_obj_t * ui_MainMenu_Label_connectStatus = NULL;
lv_obj_t * ui_MainMenu_Label_Label3 = NULL;
lv_obj_t * ui_MainMenu_Dropdown_NetworkList = NULL;
lv_obj_t * ui_MainMenu_Textarea_Password = NULL;
lv_obj_t * ui_MainMenu_Button_NetworkSave = NULL;
lv_obj_t * ui_MainMenu_Label_Label12 = NULL;
lv_obj_t * ui_MainMenu_Button_NetworkScan = NULL;
lv_obj_t * ui_MainMenu_Label_Label13 = NULL;
lv_obj_t * ui_MainMenu_Switch_Wifi = NULL;
lv_obj_t * ui_MainMenu_Tabpage_screen = NULL;
lv_obj_t * ui_MainMenu_Dropdown_Brightness = NULL;
lv_obj_t * ui_MainMenu_Dropdown_SleepTimer = NULL;
lv_obj_t * ui_MainMenu_Dropdown_Wallpaper = NULL;
lv_obj_t * ui_MainMenu_Label_Label8 = NULL;
lv_obj_t * ui_MainMenu_Tabpage_station = NULL;
lv_obj_t * ui_MainMenu_Textarea_stationList = NULL;
lv_obj_t * ui_MainMenu_Label_Label10 = NULL;
lv_obj_t * ui_MainMenu_Button_LoadStation = NULL;
lv_obj_t * ui_MainMenu_Label_Label20 = NULL;
lv_obj_t * ui_MainMenu_Tabpage_music = NULL;
lv_obj_t * ui_MainMenu_Button_scanMusic = NULL;
lv_obj_t * ui_MainMenu_Label_Label14 = NULL;
lv_obj_t * ui_MainMenu_Label_Label15 = NULL;
lv_obj_t * ui_MainMenu_Label_trackCount = NULL;
lv_obj_t * ui_MainMenu_Tabpage_region = NULL;
lv_obj_t * ui_MainMenu_Image_Globe = NULL;
lv_obj_t * ui_MainMenu_Checkbox_AutoIP = NULL;
lv_obj_t * ui_MainMenu_Textarea_Latitude = NULL;
lv_obj_t * ui_MainMenu_Textarea_Longitude = NULL;
lv_obj_t * ui_MainMenu_Image_timezone = NULL;
lv_obj_t * ui_MainMenu_Roller_Hour = NULL;
lv_obj_t * ui_MainMenu_Roller_Minute = NULL;
lv_obj_t * ui_MainMenu_Roller_Unit = NULL;
lv_obj_t * ui_MainMenu_Label_Label25 = NULL;
lv_obj_t * ui_MainMenu_Tabpage_guide = NULL;
lv_obj_t * ui_MainMenu_Textarea_UserGuide = NULL;
lv_obj_t * ui_MainMenu_Image_buttons = NULL;
lv_obj_t * ui_MainMenu_Button_closeConfig = NULL;
lv_obj_t * ui_MainMenu_Label_Label9 = NULL;
lv_obj_t * ui_MainMenu_Keyboard_Keyboard1 = NULL;
lv_obj_t * ui_MainMenu_Keyboard_Number = NULL;
lv_obj_t * ui_MainMenu_Panel_blindPanel = NULL;

// NAS Tab 页面 UI 变量
lv_obj_t * ui_MainMenu_Tabpage_nas = NULL;
lv_obj_t * ui_MainMenu_Dropdown_NasType = NULL;
lv_obj_t * ui_MainMenu_Textarea_NasIP = NULL;
lv_obj_t * ui_MainMenu_Textarea_NasPort = NULL;
lv_obj_t * ui_MainMenu_Textarea_NasUser = NULL;
lv_obj_t * ui_MainMenu_Textarea_NasPass = NULL;
lv_obj_t * ui_MainMenu_Switch_NasHttps = NULL;
lv_obj_t * ui_MainMenu_Panel_NasAuth = NULL;
lv_obj_t * ui_MainMenu_Label_NasStatus = NULL;
lv_obj_t * ui_MainMenu_Button_NasSave = NULL;
lv_obj_t * ui_MainMenu_Panel_NasExtra = NULL;
lv_obj_t * ui_MainMenu_Textarea_NasExtra1 = NULL;
lv_obj_t * ui_MainMenu_Textarea_NasExtra2 = NULL;

// 存储配置（SATA/M.2 数量）
lv_obj_t * ui_MainMenu_Dropdown_SataCount = NULL;
lv_obj_t * ui_MainMenu_Dropdown_M2Count = NULL;

// event funtions

void ui_event_MainMenu_Tabview_ConfigPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        resetScreenOffTimer(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        resetScreenOffTimer(e);
    }
}

void ui_event_MainMenu_Tabpage_network(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        resetScreenOffTimer(e);
    }
}

void ui_event_MainMenu_Textarea_Password(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_flag_modify(ui_MainMenu_Keyboard_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_MainMenu_Button_NetworkSave(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        saveWiFiCredential(e);
    }
}

void ui_event_MainMenu_Button_NetworkScan(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        scanNetwork(e);
    }
}

void ui_event_MainMenu_Switch_Wifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        toggleWiFi(e);
    }
}

void ui_event_MainMenu_Tabpage_screen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        resetScreenOffTimer(e);
    }
}

void ui_event_MainMenu_Dropdown_Brightness(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        setBrightness(e);
    }
}

void ui_event_MainMenu_Dropdown_SleepTimer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        setTimer(e);
    }
}

void ui_event_MainMenu_Dropdown_Wallpaper(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        setWallpaper(e);
    }
}

void ui_event_MainMenu_Tabpage_station(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        resetScreenOffTimer(e);
    }
}

void ui_event_MainMenu_Button_LoadStation(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        loadStationFromSDCARD(e);
    }
}

void ui_event_MainMenu_Tabpage_music(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        resetScreenOffTimer(e);
    }
}

void ui_event_MainMenu_Button_scanMusic(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        loadMusicFromSDCARD(e);
    }
}

void ui_event_MainMenu_Tabpage_region(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        resetScreenOffTimer(e);
    }
}

void ui_event_MainMenu_Checkbox_AutoIP(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        set_query_para_autoip(e);
        _ui_flag_modify(ui_MainMenu_Textarea_Latitude, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_MainMenu_Textarea_Longitude, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_flag_modify(ui_MainMenu_Textarea_Latitude, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_MainMenu_Textarea_Longitude, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_MainMenu_Textarea_Latitude(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_MainMenu_Keyboard_Number,  ui_MainMenu_Textarea_Latitude);
        _ui_flag_modify(ui_MainMenu_Keyboard_Number, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_MainMenu_Textarea_Longitude(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_MainMenu_Keyboard_Number,  ui_MainMenu_Textarea_Longitude);
        _ui_flag_modify(ui_MainMenu_Keyboard_Number, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_MainMenu_Roller_Hour(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        setOffsetHour(e);
    }
}

void ui_event_MainMenu_Roller_Minute(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        setOffsetMinute(e);
    }
}

void ui_event_MainMenu_Roller_Unit(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        setTempUnit(e);
    }
}

void ui_event_MainMenu_Tabpage_guide(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        resetScreenOffTimer(e);
    }
}

void ui_event_MainMenu_Textarea_UserGuide(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        resetScreenOffTimer(e);
    }
}

void ui_event_MainMenu_Button_closeConfig(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        saveConfig(e);
        // 切换到 Overview 页面
        if (ui_Screen_Overview != NULL) {
            lv_scr_load_anim(ui_Screen_Overview, LV_SCR_LOAD_ANIM_MOVE_TOP, 300, 0, false);
        }
    }
}

void ui_event_MainMenu_Keyboard_Keyboard1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t* keyboard = lv_event_get_target(e);

    if(event_code == LV_EVENT_READY) {
        // 按对号按钮：隐藏键盘
        lv_obj_add_flag(keyboard, LV_OBJ_FLAG_HIDDEN);
    }
    else if(event_code == LV_EVENT_CANCEL) {
        // 按取消按钮：隐藏键盘
        lv_obj_add_flag(keyboard, LV_OBJ_FLAG_HIDDEN);
    }
}

void ui_event_MainMenu_Keyboard_Number(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t* keyboard = lv_event_get_target(e);

    if(event_code == LV_EVENT_READY) {
        // 按对号按钮：隐藏键盘
        lv_obj_add_flag(keyboard, LV_OBJ_FLAG_HIDDEN);
    }
    else if(event_code == LV_EVENT_CANCEL) {
        // 按取消按钮：隐藏键盘
        lv_obj_add_flag(keyboard, LV_OBJ_FLAG_HIDDEN);
    }
}

void ui_event_MainMenu_Panel_blindPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        turnonScreen(e);
    }
}

// build funtions

void ui_Screen_Settings_screen_init(void)
{
    ui_Screen_Settings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen_Settings,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_Screen_Settings, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainMenu_Tabview_ConfigPanel = lv_tabview_create(ui_Screen_Settings, LV_DIR_BOTTOM, 40);
    lv_obj_set_width(ui_MainMenu_Tabview_ConfigPanel, lv_pct(100));
    lv_obj_set_height(ui_MainMenu_Tabview_ConfigPanel, lv_pct(100));
    lv_obj_set_align(ui_MainMenu_Tabview_ConfigPanel, LV_ALIGN_CENTER);
    // 保留 GESTURE_BUBBLE 让手势能传递到父对象
    lv_obj_clear_flag(ui_MainMenu_Tabview_ConfigPanel,
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_MainMenu_Tabview_ConfigPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainMenu_Tabview_ConfigPanel, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_MainMenu_Tabview_ConfigPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MainMenu_Tabview_ConfigPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_MainMenu_Tabview_ConfigPanel), lv_color_hex(0x00ADFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_MainMenu_Tabview_ConfigPanel), 255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(lv_tabview_get_tab_btns(ui_MainMenu_Tabview_ConfigPanel), lv_color_hex(0x025074),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(lv_tabview_get_tab_btns(ui_MainMenu_Tabview_ConfigPanel), LV_GRAD_DIR_VER,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_MainMenu_Tabview_ConfigPanel), lv_color_hex(0x000000),
                                LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_MainMenu_Tabview_ConfigPanel), 255,
                              LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_MainMenu_Tabview_ConfigPanel), lv_color_hex(0xFFFFFF),
                              LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_MainMenu_Tabview_ConfigPanel), 255,
                            LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(lv_tabview_get_tab_btns(ui_MainMenu_Tabview_ConfigPanel), lv_color_hex(0x9D9C9C),
                                   LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(lv_tabview_get_tab_btns(ui_MainMenu_Tabview_ConfigPanel), LV_GRAD_DIR_VER,
                                 LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(lv_tabview_get_tab_btns(ui_MainMenu_Tabview_ConfigPanel), lv_color_hex(0x000000),
                                  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(lv_tabview_get_tab_btns(ui_MainMenu_Tabview_ConfigPanel), 255,
                                LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(lv_tabview_get_tab_btns(ui_MainMenu_Tabview_ConfigPanel), 2,
                                  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_MainMenu_Tabview_ConfigPanel), lv_color_hex(0xFFFFFF),
                                LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_MainMenu_Tabview_ConfigPanel), 255,
                              LV_PART_ITEMS | LV_STATE_CHECKED);

    // ============================================================
    // NAS Tab 页面 - NAS 类型选择和连接配置
    // ============================================================
    ui_MainMenu_Tabpage_nas = lv_tabview_add_tab(ui_MainMenu_Tabview_ConfigPanel, "NAS");
    lv_obj_set_scrollbar_mode(ui_MainMenu_Tabpage_nas, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_MainMenu_Tabpage_nas, LV_DIR_VER);

    // NAS 类型标签
    lv_obj_t * ui_Label_NasType = lv_label_create(ui_MainMenu_Tabpage_nas);
    lv_obj_set_width(ui_Label_NasType, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Label_NasType, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Label_NasType, 8);
    lv_obj_set_y(ui_Label_NasType, 8);
    lv_label_set_text(ui_Label_NasType, "NAS Type:");
    lv_obj_set_style_text_font(ui_Label_NasType, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label_NasType, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);

    // NAS 类型下拉选择
    ui_MainMenu_Dropdown_NasType = lv_dropdown_create(ui_MainMenu_Tabpage_nas);
    lv_dropdown_set_options(ui_MainMenu_Dropdown_NasType,
        "Synology DSM\n"
        "QNAP QTS\n"
        "TrueNAS\n"
        "FNOS\n"
        "Unraid\n"
        "Netdata\n"
        "SNMP\n"
        "Linux (HTTP)\n"
        "Linux (Serial)\n"
        "Windows\n"
        "Mock (Test)");
    lv_obj_set_width(ui_MainMenu_Dropdown_NasType, 200);
    lv_obj_set_height(ui_MainMenu_Dropdown_NasType, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_MainMenu_Dropdown_NasType, 100);
    lv_obj_set_y(ui_MainMenu_Dropdown_NasType, 4);
    lv_obj_add_flag(ui_MainMenu_Dropdown_NasType, LV_OBJ_FLAG_SCROLL_ON_FOCUS);

    // ============================================================
    // 存储配置区域（SATA/M.2 数量）- 暂时注释以排查白屏问题
    // ============================================================
    #if 0
    lv_obj_t * ui_Label_Storage = lv_label_create(ui_MainMenu_Tabpage_nas);
    lv_obj_set_width(ui_Label_Storage, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Label_Storage, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Label_Storage, 320);
    lv_obj_set_y(ui_Label_Storage, 8);
    lv_label_set_text(ui_Label_Storage, "Storage:");
    lv_obj_set_style_text_font(ui_Label_Storage, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label_Storage, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT);

    // SATA 数量标签
    lv_obj_t * ui_Label_Sata = lv_label_create(ui_MainMenu_Tabpage_nas);
    lv_obj_set_width(ui_Label_Sata, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Label_Sata, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Label_Sata, 400);
    lv_obj_set_y(ui_Label_Sata, 8);
    lv_label_set_text(ui_Label_Sata, "SATA:");
    lv_obj_set_style_text_font(ui_Label_Sata, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label_Sata, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);

    // SATA 数量下拉
    ui_MainMenu_Dropdown_SataCount = lv_dropdown_create(ui_MainMenu_Tabpage_nas);
    lv_dropdown_set_options(ui_MainMenu_Dropdown_SataCount,
        "0\n1\n2\n3\n4\n5\n6\n7\n8");
    lv_obj_set_width(ui_MainMenu_Dropdown_SataCount, 70);
    lv_obj_set_height(ui_MainMenu_Dropdown_SataCount, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_MainMenu_Dropdown_SataCount, 455);
    lv_obj_set_y(ui_MainMenu_Dropdown_SataCount, 4);
    // lv_dropdown_set_selected(ui_MainMenu_Dropdown_SataCount, 6);  // 默认 6 个

    // M.2 数量标签
    lv_obj_t * ui_Label_M2 = lv_label_create(ui_MainMenu_Tabpage_nas);
    lv_obj_set_width(ui_Label_M2, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Label_M2, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Label_M2, 535);
    lv_obj_set_y(ui_Label_M2, 8);
    lv_label_set_text(ui_Label_M2, "M.2:");
    lv_obj_set_style_text_font(ui_Label_M2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label_M2, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);

    // M.2 数量下拉
    ui_MainMenu_Dropdown_M2Count = lv_dropdown_create(ui_MainMenu_Tabpage_nas);
    lv_dropdown_set_options(ui_MainMenu_Dropdown_M2Count,
        "0\n1\n2\n3\n4\n5\n6\n7\n8");
    lv_obj_set_width(ui_MainMenu_Dropdown_M2Count, 60);
    lv_obj_set_height(ui_MainMenu_Dropdown_M2Count, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_MainMenu_Dropdown_M2Count, 575);
    lv_obj_set_y(ui_MainMenu_Dropdown_M2Count, 4);
    // lv_dropdown_set_selected(ui_MainMenu_Dropdown_M2Count, 3);  // 默认 3 个
    #endif

    // IP 地址标签
    lv_obj_t * ui_Label_NasIP = lv_label_create(ui_MainMenu_Tabpage_nas);
    lv_obj_set_width(ui_Label_NasIP, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Label_NasIP, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Label_NasIP, 8);
    lv_obj_set_y(ui_Label_NasIP, 38);
    lv_label_set_text(ui_Label_NasIP, "IP:");
    lv_obj_set_style_text_font(ui_Label_NasIP, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label_NasIP, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);

    // IP 地址输入框
    ui_MainMenu_Textarea_NasIP = lv_textarea_create(ui_MainMenu_Tabpage_nas);
    lv_obj_set_width(ui_MainMenu_Textarea_NasIP, 200);
    lv_obj_set_height(ui_MainMenu_Textarea_NasIP, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_MainMenu_Textarea_NasIP, 100);
    lv_obj_set_y(ui_MainMenu_Textarea_NasIP, 34);
    lv_textarea_set_placeholder_text(ui_MainMenu_Textarea_NasIP, "192.168.1.100");
    lv_textarea_set_max_length(ui_MainMenu_Textarea_NasIP, 40);
    lv_textarea_set_one_line(ui_MainMenu_Textarea_NasIP, true);
    lv_obj_set_style_text_font(ui_MainMenu_Textarea_NasIP, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 端口标签
    lv_obj_t * ui_Label_NasPort = lv_label_create(ui_MainMenu_Tabpage_nas);
    lv_obj_set_width(ui_Label_NasPort, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Label_NasPort, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Label_NasPort, 320);
    lv_obj_set_y(ui_Label_NasPort, 38);
    lv_label_set_text(ui_Label_NasPort, "Port:");
    lv_obj_set_style_text_font(ui_Label_NasPort, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label_NasPort, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);

    // 端口输入框
    ui_MainMenu_Textarea_NasPort = lv_textarea_create(ui_MainMenu_Tabpage_nas);
    lv_obj_set_width(ui_MainMenu_Textarea_NasPort, 80);
    lv_obj_set_height(ui_MainMenu_Textarea_NasPort, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_MainMenu_Textarea_NasPort, 370);
    lv_obj_set_y(ui_MainMenu_Textarea_NasPort, 34);
    lv_textarea_set_placeholder_text(ui_MainMenu_Textarea_NasPort, "5000");
    lv_textarea_set_max_length(ui_MainMenu_Textarea_NasPort, 5);
    lv_textarea_set_one_line(ui_MainMenu_Textarea_NasPort, true);
    lv_obj_set_style_text_font(ui_MainMenu_Textarea_NasPort, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // HTTPS 开关
    ui_MainMenu_Switch_NasHttps = lv_switch_create(ui_MainMenu_Tabpage_nas);
    lv_obj_set_width(ui_MainMenu_Switch_NasHttps, 50);
    lv_obj_set_height(ui_MainMenu_Switch_NasHttps, 24);
    lv_obj_set_x(ui_MainMenu_Switch_NasHttps, 470);
    lv_obj_set_y(ui_MainMenu_Switch_NasHttps, 36);
    lv_obj_set_style_bg_color(ui_MainMenu_Switch_NasHttps, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainMenu_Switch_NasHttps, lv_color_hex(0x088CFD), LV_PART_INDICATOR | LV_STATE_CHECKED);

    // HTTPS 标签
    lv_obj_t * ui_Label_Https = lv_label_create(ui_MainMenu_Tabpage_nas);
    lv_obj_set_width(ui_Label_Https, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Label_Https, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Label_Https, 530);
    lv_obj_set_y(ui_Label_Https, 38);
    lv_label_set_text(ui_Label_Https, "HTTPS");
    lv_obj_set_style_text_font(ui_Label_Https, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 认证信息面板（用户名/密码）
    ui_MainMenu_Panel_NasAuth = lv_obj_create(ui_MainMenu_Tabpage_nas);
    lv_obj_set_width(ui_MainMenu_Panel_NasAuth, lv_pct(100));
    lv_obj_set_height(ui_MainMenu_Panel_NasAuth, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_MainMenu_Panel_NasAuth, 0);
    lv_obj_set_y(ui_MainMenu_Panel_NasAuth, 64);
    lv_obj_set_scrollbar_mode(ui_MainMenu_Panel_NasAuth, LV_SCROLLBAR_MODE_OFF);
    lv_obj_clear_flag(ui_MainMenu_Panel_NasAuth, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_opa(ui_MainMenu_Panel_NasAuth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MainMenu_Panel_NasAuth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 用户名标签
    lv_obj_t * ui_Label_NasUser = lv_label_create(ui_MainMenu_Panel_NasAuth);
    lv_obj_set_width(ui_Label_NasUser, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Label_NasUser, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Label_NasUser, 8);
    lv_obj_set_y(ui_Label_NasUser, 0);
    lv_label_set_text(ui_Label_NasUser, "User:");
    lv_obj_set_style_text_font(ui_Label_NasUser, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label_NasUser, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);

    // 用户名输入框
    ui_MainMenu_Textarea_NasUser = lv_textarea_create(ui_MainMenu_Panel_NasAuth);
    lv_obj_set_width(ui_MainMenu_Textarea_NasUser, 150);
    lv_obj_set_height(ui_MainMenu_Textarea_NasUser, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_MainMenu_Textarea_NasUser, 60);
    lv_obj_set_y(ui_MainMenu_Textarea_NasUser, -4);
    lv_textarea_set_placeholder_text(ui_MainMenu_Textarea_NasUser, "admin");
    lv_textarea_set_max_length(ui_MainMenu_Textarea_NasUser, 32);
    lv_textarea_set_one_line(ui_MainMenu_Textarea_NasUser, true);
    lv_obj_set_style_text_font(ui_MainMenu_Textarea_NasUser, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 密码标签
    lv_obj_t * ui_Label_NasPass = lv_label_create(ui_MainMenu_Panel_NasAuth);
    lv_obj_set_width(ui_Label_NasPass, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Label_NasPass, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Label_NasPass, 230);
    lv_obj_set_y(ui_Label_NasPass, 0);
    lv_label_set_text(ui_Label_NasPass, "Pass:");
    lv_obj_set_style_text_font(ui_Label_NasPass, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label_NasPass, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);

    // 密码输入框
    ui_MainMenu_Textarea_NasPass = lv_textarea_create(ui_MainMenu_Panel_NasAuth);
    lv_obj_set_width(ui_MainMenu_Textarea_NasPass, 180);
    lv_obj_set_height(ui_MainMenu_Textarea_NasPass, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_MainMenu_Textarea_NasPass, 290);
    lv_obj_set_y(ui_MainMenu_Textarea_NasPass, -4);
    lv_textarea_set_placeholder_text(ui_MainMenu_Textarea_NasPass, "password");
    lv_textarea_set_max_length(ui_MainMenu_Textarea_NasPass, 65);
    lv_textarea_set_one_line(ui_MainMenu_Textarea_NasPass, true);
    lv_textarea_set_password_mode(ui_MainMenu_Textarea_NasPass, true);
    lv_obj_set_style_text_font(ui_MainMenu_Textarea_NasPass, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 额外配置面板（SNMP/Serial等）
    ui_MainMenu_Panel_NasExtra = lv_obj_create(ui_MainMenu_Tabpage_nas);
    lv_obj_set_width(ui_MainMenu_Panel_NasExtra, lv_pct(100));
    lv_obj_set_height(ui_MainMenu_Panel_NasExtra, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_MainMenu_Panel_NasExtra, 0);
    lv_obj_set_y(ui_MainMenu_Panel_NasExtra, 100);
    lv_obj_set_scrollbar_mode(ui_MainMenu_Panel_NasExtra, LV_SCROLLBAR_MODE_OFF);
    lv_obj_clear_flag(ui_MainMenu_Panel_NasExtra, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_opa(ui_MainMenu_Panel_NasExtra, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MainMenu_Panel_NasExtra, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_MainMenu_Panel_NasExtra, LV_OBJ_FLAG_HIDDEN);

    // 额外配置标签1
    lv_obj_t * ui_Label_NasExtra1 = lv_label_create(ui_MainMenu_Panel_NasExtra);
    lv_obj_set_width(ui_Label_NasExtra1, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Label_NasExtra1, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Label_NasExtra1, 8);
    lv_obj_set_y(ui_Label_NasExtra1, 0);
    lv_label_set_text(ui_Label_NasExtra1, "SNMP Community:");
    lv_obj_set_style_text_font(ui_Label_NasExtra1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label_NasExtra1, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);

    // 额外配置输入1
    ui_MainMenu_Textarea_NasExtra1 = lv_textarea_create(ui_MainMenu_Panel_NasExtra);
    lv_obj_set_width(ui_MainMenu_Textarea_NasExtra1, 200);
    lv_obj_set_height(ui_MainMenu_Textarea_NasExtra1, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_MainMenu_Textarea_NasExtra1, 130);
    lv_obj_set_y(ui_MainMenu_Textarea_NasExtra1, -4);
    lv_textarea_set_placeholder_text(ui_MainMenu_Textarea_NasExtra1, "public");
    lv_textarea_set_max_length(ui_MainMenu_Textarea_NasExtra1, 32);
    lv_textarea_set_one_line(ui_MainMenu_Textarea_NasExtra1, true);
    lv_obj_set_style_text_font(ui_MainMenu_Textarea_NasExtra1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 额外配置标签2
    lv_obj_t * ui_Label_NasExtra2 = lv_label_create(ui_MainMenu_Panel_NasExtra);
    lv_obj_set_width(ui_Label_NasExtra2, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Label_NasExtra2, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Label_NasExtra2, 350);
    lv_obj_set_y(ui_Label_NasExtra2, 0);
    lv_label_set_text(ui_Label_NasExtra2, "SNMP Ver:");
    lv_obj_set_style_text_font(ui_Label_NasExtra2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label_NasExtra2, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);

    // 额外配置输入2 (SNMP版本下拉)
    ui_MainMenu_Textarea_NasExtra2 = lv_dropdown_create(ui_MainMenu_Panel_NasExtra);
    lv_dropdown_set_options(ui_MainMenu_Textarea_NasExtra2, "v1\nv2c\nv3");
    lv_obj_set_width(ui_MainMenu_Textarea_NasExtra2, 100);
    lv_obj_set_height(ui_MainMenu_Textarea_NasExtra2, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_MainMenu_Textarea_NasExtra2, 430);
    lv_obj_set_y(ui_MainMenu_Textarea_NasExtra2, -2);

    // 状态标签
    ui_MainMenu_Label_NasStatus = lv_label_create(ui_MainMenu_Tabpage_nas);
    lv_obj_set_width(ui_MainMenu_Label_NasStatus, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_MainMenu_Label_NasStatus, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_MainMenu_Label_NasStatus, 8);
    lv_obj_set_y(ui_MainMenu_Label_NasStatus, 110);
    lv_label_set_text(ui_MainMenu_Label_NasStatus, "Not configured");
    lv_obj_set_style_text_font(ui_MainMenu_Label_NasStatus, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_MainMenu_Label_NasStatus, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);

    // 保存按钮
    ui_MainMenu_Button_NasSave = lv_btn_create(ui_MainMenu_Tabpage_nas);
    lv_obj_set_width(ui_MainMenu_Button_NasSave, 120);
    lv_obj_set_height(ui_MainMenu_Button_NasSave, 44);
    lv_obj_set_x(ui_MainMenu_Button_NasSave, 490);
    lv_obj_set_y(ui_MainMenu_Button_NasSave, 100);
    lv_obj_add_flag(ui_MainMenu_Button_NasSave, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_MainMenu_Button_NasSave, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_MainMenu_Button_NasSave, lv_color_hex(0x00ADFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainMenu_Button_NasSave, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MainMenu_Button_NasSave, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_MainMenu_Button_NasSave, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * ui_Label_NasSave = lv_label_create(ui_MainMenu_Button_NasSave);
    lv_obj_set_width(ui_Label_NasSave, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Label_NasSave, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_Label_NasSave, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_NasSave, "D Save");
    lv_obj_set_style_text_font(ui_Label_NasSave, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label_NasSave, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    // NAS Tab UI 创建结束

    ui_MainMenu_Tabpage_network = lv_tabview_add_tab(ui_MainMenu_Tabview_ConfigPanel, "Wi-Fi");
    lv_obj_set_scrollbar_mode(ui_MainMenu_Tabpage_network, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_MainMenu_Tabpage_network, LV_DIR_HOR);

    ui_MainMenu_Label_connectStatus = lv_label_create(ui_MainMenu_Tabpage_network);
    lv_obj_set_width(ui_MainMenu_Label_connectStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainMenu_Label_connectStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainMenu_Label_connectStatus, 60);
    lv_obj_set_y(ui_MainMenu_Label_connectStatus, 12);
    lv_obj_set_align(ui_MainMenu_Label_connectStatus, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_MainMenu_Label_connectStatus, "Disconnected");
    lv_obj_set_style_text_color(ui_MainMenu_Label_connectStatus, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MainMenu_Label_connectStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainMenu_Label_Label3 = lv_label_create(ui_MainMenu_Tabpage_network);
    lv_obj_set_width(ui_MainMenu_Label_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainMenu_Label_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainMenu_Label_Label3, -11);
    lv_obj_set_y(ui_MainMenu_Label_Label3, -2);
    lv_label_set_text(ui_MainMenu_Label_Label3,
                      "SSID:                                                                                        Max 10\n-------																							                                          Slot\nPass:                                                                                        \n-------                                                                                       Wi-Fi\nStatus:");
    lv_obj_clear_flag(ui_MainMenu_Label_Label3,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_letter_space(ui_MainMenu_Label_Label3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_MainMenu_Label_Label3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainMenu_Dropdown_NetworkList = lv_dropdown_create(ui_MainMenu_Tabpage_network);
    lv_dropdown_set_options(ui_MainMenu_Dropdown_NetworkList, "");
    lv_obj_set_width(ui_MainMenu_Dropdown_NetworkList, 260);
    lv_obj_set_height(ui_MainMenu_Dropdown_NetworkList, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_MainMenu_Dropdown_NetworkList, 50);
    lv_obj_set_y(ui_MainMenu_Dropdown_NetworkList, -15);
    lv_obj_add_flag(ui_MainMenu_Dropdown_NetworkList, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_MainMenu_Textarea_Password = lv_textarea_create(ui_MainMenu_Tabpage_network);
    lv_obj_set_width(ui_MainMenu_Textarea_Password, 260);
    lv_obj_set_height(ui_MainMenu_Textarea_Password, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_MainMenu_Textarea_Password, 50);
    lv_obj_set_y(ui_MainMenu_Textarea_Password, 38);
    lv_textarea_set_max_length(ui_MainMenu_Textarea_Password, 32);
    lv_textarea_set_placeholder_text(ui_MainMenu_Textarea_Password, "Wi-Fi Password");
    lv_textarea_set_one_line(ui_MainMenu_Textarea_Password, true);

    lv_obj_set_style_border_color(ui_MainMenu_Textarea_Password, lv_color_hex(0x000000), LV_PART_CURSOR | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_MainMenu_Textarea_Password, 255, LV_PART_CURSOR | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_MainMenu_Textarea_Password, 1, LV_PART_CURSOR | LV_STATE_FOCUSED);
    lv_obj_set_style_border_side(ui_MainMenu_Textarea_Password, LV_BORDER_SIDE_LEFT, LV_PART_CURSOR | LV_STATE_FOCUSED);

    ui_MainMenu_Button_NetworkSave = lv_btn_create(ui_MainMenu_Tabpage_network);
    lv_obj_set_width(ui_MainMenu_Button_NetworkSave, 150);
    lv_obj_set_height(ui_MainMenu_Button_NetworkSave, 50);
    lv_obj_set_x(ui_MainMenu_Button_NetworkSave, 85);
    lv_obj_set_y(ui_MainMenu_Button_NetworkSave, 10);
    lv_obj_set_align(ui_MainMenu_Button_NetworkSave, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MainMenu_Button_NetworkSave, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MainMenu_Button_NetworkSave, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainMenu_Button_NetworkSave, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainMenu_Button_NetworkSave, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MainMenu_Button_NetworkSave, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MainMenu_Button_NetworkSave, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MainMenu_Button_NetworkSave, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainMenu_Label_Label12 = lv_label_create(ui_MainMenu_Button_NetworkSave);
    lv_obj_set_width(ui_MainMenu_Label_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainMenu_Label_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MainMenu_Label_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MainMenu_Label_Label12, "D Save");
    lv_obj_set_style_text_font(ui_MainMenu_Label_Label12, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainMenu_Button_NetworkScan = lv_btn_create(ui_MainMenu_Tabpage_network);
    lv_obj_set_width(ui_MainMenu_Button_NetworkScan, 150);
    lv_obj_set_height(ui_MainMenu_Button_NetworkScan, 50);
    lv_obj_set_x(ui_MainMenu_Button_NetworkScan, 85);
    lv_obj_set_y(ui_MainMenu_Button_NetworkScan, -42);
    lv_obj_set_align(ui_MainMenu_Button_NetworkScan, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MainMenu_Button_NetworkScan, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MainMenu_Button_NetworkScan, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainMenu_Button_NetworkScan, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainMenu_Button_NetworkScan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MainMenu_Button_NetworkScan, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MainMenu_Button_NetworkScan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MainMenu_Button_NetworkScan, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainMenu_Label_Label13 = lv_label_create(ui_MainMenu_Button_NetworkScan);
    lv_obj_set_width(ui_MainMenu_Label_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainMenu_Label_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MainMenu_Label_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MainMenu_Label_Label13, "W Scan");
    lv_obj_set_style_text_font(ui_MainMenu_Label_Label13, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainMenu_Switch_Wifi = lv_switch_create(ui_MainMenu_Tabpage_network);
    lv_obj_add_state(ui_MainMenu_Switch_Wifi, LV_STATE_CHECKED);
    lv_obj_set_width(ui_MainMenu_Switch_Wifi, 60);
    lv_obj_set_height(ui_MainMenu_Switch_Wifi, 29);
    lv_obj_set_x(ui_MainMenu_Switch_Wifi, 0);
    lv_obj_set_y(ui_MainMenu_Switch_Wifi, -9);
    lv_obj_set_align(ui_MainMenu_Switch_Wifi, LV_ALIGN_BOTTOM_RIGHT);

    lv_obj_set_style_bg_color(ui_MainMenu_Switch_Wifi, lv_color_hex(0x088CFD), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_MainMenu_Switch_Wifi, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_MainMenu_Switch_Wifi, lv_color_hex(0x0845FA), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainMenu_Switch_Wifi, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_MainMenu_Tabpage_screen = lv_tabview_add_tab(ui_MainMenu_Tabview_ConfigPanel, "Screen");
    lv_obj_set_scrollbar_mode(ui_MainMenu_Tabpage_screen, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_MainMenu_Tabpage_screen, LV_DIR_HOR);

    ui_MainMenu_Dropdown_Brightness = lv_dropdown_create(ui_MainMenu_Tabpage_screen);
    lv_dropdown_set_options(ui_MainMenu_Dropdown_Brightness, "LOW\nMEDIUM\nHIGH");
    lv_obj_set_width(ui_MainMenu_Dropdown_Brightness, 150);
    lv_obj_set_height(ui_MainMenu_Dropdown_Brightness, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainMenu_Dropdown_Brightness, 0);
    lv_obj_set_y(ui_MainMenu_Dropdown_Brightness, 15);
    lv_obj_add_flag(ui_MainMenu_Dropdown_Brightness, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_MainMenu_Dropdown_SleepTimer = lv_dropdown_create(ui_MainMenu_Tabpage_screen);
    lv_dropdown_set_options(ui_MainMenu_Dropdown_SleepTimer, "0\n15\n30\n60");
    lv_obj_set_width(ui_MainMenu_Dropdown_SleepTimer, 150);
    lv_obj_set_height(ui_MainMenu_Dropdown_SleepTimer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainMenu_Dropdown_SleepTimer, 180);
    lv_obj_set_y(ui_MainMenu_Dropdown_SleepTimer, 15);
    lv_obj_add_flag(ui_MainMenu_Dropdown_SleepTimer, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_MainMenu_Dropdown_Wallpaper = lv_dropdown_create(ui_MainMenu_Tabpage_screen);
    lv_dropdown_set_options(ui_MainMenu_Dropdown_Wallpaper, "");
    lv_obj_set_width(ui_MainMenu_Dropdown_Wallpaper, 150);
    lv_obj_set_height(ui_MainMenu_Dropdown_Wallpaper, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainMenu_Dropdown_Wallpaper, 360);
    lv_obj_set_y(ui_MainMenu_Dropdown_Wallpaper, 15);
    lv_obj_add_flag(ui_MainMenu_Dropdown_Wallpaper, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_MainMenu_Label_Label8 = lv_label_create(ui_MainMenu_Tabpage_screen);
    lv_obj_set_width(ui_MainMenu_Label_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainMenu_Label_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainMenu_Label_Label8, 26);
    lv_obj_set_y(ui_MainMenu_Label_Label8, -15);
    lv_label_set_text(ui_MainMenu_Label_Label8, "Brightness        Screen off timer (sec)     Wallpaper");

    ui_MainMenu_Tabpage_station = lv_tabview_add_tab(ui_MainMenu_Tabview_ConfigPanel, "Radio");
    lv_obj_set_scrollbar_mode(ui_MainMenu_Tabpage_station, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_MainMenu_Tabpage_station, LV_DIR_HOR);

    ui_MainMenu_Textarea_stationList = lv_textarea_create(ui_MainMenu_Tabpage_station);
    lv_obj_set_width(ui_MainMenu_Textarea_stationList, 320);
    lv_obj_set_height(ui_MainMenu_Textarea_stationList, 128);
    lv_obj_set_x(ui_MainMenu_Textarea_stationList, -12);
    lv_obj_set_y(ui_MainMenu_Textarea_stationList, -16);
    lv_textarea_set_placeholder_text(ui_MainMenu_Textarea_stationList, "Station URL List");
    lv_obj_set_scroll_dir(ui_MainMenu_Textarea_stationList, LV_DIR_VER);
    lv_obj_set_style_text_color(ui_MainMenu_Textarea_stationList, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MainMenu_Textarea_stationList, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MainMenu_Textarea_stationList, &ui_font_NotoSanThai16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainMenu_Textarea_stationList, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainMenu_Textarea_stationList, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainMenu_Label_Label10 = lv_label_create(ui_MainMenu_Tabpage_station);
    lv_obj_set_width(ui_MainMenu_Label_Label10, 300);
    lv_obj_set_height(ui_MainMenu_Label_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainMenu_Label_Label10, 11);
    lv_obj_set_y(ui_MainMenu_Label_Label10, 13);
    lv_obj_set_align(ui_MainMenu_Label_Label10, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_MainMenu_Label_Label10,
                      "Insert a microSD card with filename\n[ stations.csv ]  click Load.\nDefaults will be used\nif the file is unavailable.");
    lv_obj_set_scrollbar_mode(ui_MainMenu_Label_Label10, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_font(ui_MainMenu_Label_Label10, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainMenu_Button_LoadStation = lv_btn_create(ui_MainMenu_Tabpage_station);
    lv_obj_set_width(ui_MainMenu_Button_LoadStation, 144);
    lv_obj_set_height(ui_MainMenu_Button_LoadStation, 50);
    lv_obj_set_x(ui_MainMenu_Button_LoadStation, 88);
    lv_obj_set_y(ui_MainMenu_Button_LoadStation, -13);
    lv_obj_set_align(ui_MainMenu_Button_LoadStation, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_MainMenu_Button_LoadStation, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MainMenu_Button_LoadStation, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainMenu_Button_LoadStation, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainMenu_Button_LoadStation, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MainMenu_Button_LoadStation, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MainMenu_Button_LoadStation, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MainMenu_Button_LoadStation, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainMenu_Label_Label20 = lv_label_create(ui_MainMenu_Button_LoadStation);
    lv_obj_set_width(ui_MainMenu_Label_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainMenu_Label_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainMenu_Label_Label20, 1);
    lv_obj_set_y(ui_MainMenu_Label_Label20, 0);
    lv_obj_set_align(ui_MainMenu_Label_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MainMenu_Label_Label20, "D Load");
    lv_obj_set_style_text_font(ui_MainMenu_Label_Label20, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainMenu_Tabpage_music = lv_tabview_add_tab(ui_MainMenu_Tabview_ConfigPanel, "Music");
    lv_obj_set_scrollbar_mode(ui_MainMenu_Tabpage_music, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_MainMenu_Tabpage_music, LV_DIR_HOR);

    ui_MainMenu_Button_scanMusic = lv_btn_create(ui_MainMenu_Tabpage_music);
    lv_obj_set_width(ui_MainMenu_Button_scanMusic, 144);
    lv_obj_set_height(ui_MainMenu_Button_scanMusic, 50);
    lv_obj_set_x(ui_MainMenu_Button_scanMusic, -6);
    lv_obj_set_y(ui_MainMenu_Button_scanMusic, 0);
    lv_obj_set_align(ui_MainMenu_Button_scanMusic, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_MainMenu_Button_scanMusic, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MainMenu_Button_scanMusic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainMenu_Button_scanMusic, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainMenu_Button_scanMusic, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MainMenu_Button_scanMusic, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MainMenu_Button_scanMusic, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MainMenu_Button_scanMusic, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainMenu_Label_Label14 = lv_label_create(ui_MainMenu_Button_scanMusic);
    lv_obj_set_width(ui_MainMenu_Label_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainMenu_Label_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainMenu_Label_Label14, 1);
    lv_obj_set_y(ui_MainMenu_Label_Label14, 0);
    lv_obj_set_align(ui_MainMenu_Label_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MainMenu_Label_Label14, "D Load");
    lv_obj_set_style_text_font(ui_MainMenu_Label_Label14, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainMenu_Label_Label15 = lv_label_create(ui_MainMenu_Tabpage_music);
    lv_obj_set_width(ui_MainMenu_Label_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainMenu_Label_Label15, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_MainMenu_Label_Label15, "Tap  LOAD to refresh the music library from the SD card");

    ui_MainMenu_Label_trackCount = lv_label_create(ui_MainMenu_Tabpage_music);
    lv_obj_set_width(ui_MainMenu_Label_trackCount, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainMenu_Label_trackCount, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainMenu_Label_trackCount, 150);
    lv_obj_set_y(ui_MainMenu_Label_trackCount, -9);
    lv_obj_set_align(ui_MainMenu_Label_trackCount, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_long_mode(ui_MainMenu_Label_trackCount, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_MainMenu_Label_trackCount, "Card Mount Failed");
    lv_obj_set_style_text_font(ui_MainMenu_Label_trackCount, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainMenu_Tabpage_region = lv_tabview_add_tab(ui_MainMenu_Tabview_ConfigPanel, "Region");
    lv_obj_set_scrollbar_mode(ui_MainMenu_Tabpage_region, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_MainMenu_Tabpage_region, LV_DIR_HOR);

    ui_MainMenu_Image_Globe = lv_img_create(ui_MainMenu_Tabpage_region);
    lv_img_set_src(ui_MainMenu_Image_Globe, &ui_img_images_globe_png);
    lv_obj_set_width(ui_MainMenu_Image_Globe, LV_SIZE_CONTENT);   /// 120
    lv_obj_set_height(ui_MainMenu_Image_Globe, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_x(ui_MainMenu_Image_Globe, -12);
    lv_obj_set_y(ui_MainMenu_Image_Globe, 0);
    lv_obj_set_align(ui_MainMenu_Image_Globe, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_MainMenu_Image_Globe, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_MainMenu_Image_Globe, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MainMenu_Checkbox_AutoIP = lv_checkbox_create(ui_MainMenu_Tabpage_region);
    lv_checkbox_set_text(ui_MainMenu_Checkbox_AutoIP, "Auto by IP");
    lv_obj_set_width(ui_MainMenu_Checkbox_AutoIP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainMenu_Checkbox_AutoIP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainMenu_Checkbox_AutoIP, 118);
    lv_obj_set_y(ui_MainMenu_Checkbox_AutoIP, -11);
    lv_obj_add_flag(ui_MainMenu_Checkbox_AutoIP, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_MainMenu_Textarea_Latitude = lv_textarea_create(ui_MainMenu_Tabpage_region);
    lv_obj_set_width(ui_MainMenu_Textarea_Latitude, 150);
    lv_obj_set_height(ui_MainMenu_Textarea_Latitude, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_MainMenu_Textarea_Latitude, 117);
    lv_obj_set_y(ui_MainMenu_Textarea_Latitude, 23);
    lv_textarea_set_accepted_chars(ui_MainMenu_Textarea_Latitude, "0123456789.-");
    lv_textarea_set_max_length(ui_MainMenu_Textarea_Latitude, 12);
    lv_textarea_set_placeholder_text(ui_MainMenu_Textarea_Latitude, "Latitude");
    lv_textarea_set_one_line(ui_MainMenu_Textarea_Latitude, true);
    lv_obj_set_scrollbar_mode(ui_MainMenu_Textarea_Latitude, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_MainMenu_Textarea_Latitude, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MainMenu_Textarea_Latitude, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_MainMenu_Textarea_Latitude, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MainMenu_Textarea_Latitude, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_MainMenu_Textarea_Latitude, lv_color_hex(0x000000), LV_PART_CURSOR | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_MainMenu_Textarea_Latitude, 255, LV_PART_CURSOR | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_MainMenu_Textarea_Latitude, 1, LV_PART_CURSOR | LV_STATE_FOCUSED);
    lv_obj_set_style_border_side(ui_MainMenu_Textarea_Latitude, LV_BORDER_SIDE_LEFT, LV_PART_CURSOR | LV_STATE_FOCUSED);

    lv_obj_set_style_text_color(ui_MainMenu_Textarea_Latitude, lv_color_hex(0x555555),
                                LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MainMenu_Textarea_Latitude, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_MainMenu_Textarea_Longitude = lv_textarea_create(ui_MainMenu_Tabpage_region);
    lv_obj_set_width(ui_MainMenu_Textarea_Longitude, 150);
    lv_obj_set_height(ui_MainMenu_Textarea_Longitude, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_MainMenu_Textarea_Longitude, 117);
    lv_obj_set_y(ui_MainMenu_Textarea_Longitude, 70);
    lv_textarea_set_accepted_chars(ui_MainMenu_Textarea_Longitude, "0123456789.-");
    lv_textarea_set_max_length(ui_MainMenu_Textarea_Longitude, 12);
    lv_textarea_set_placeholder_text(ui_MainMenu_Textarea_Longitude, "Longitude");
    lv_textarea_set_one_line(ui_MainMenu_Textarea_Longitude, true);
    lv_obj_set_scrollbar_mode(ui_MainMenu_Textarea_Longitude, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_MainMenu_Textarea_Longitude, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MainMenu_Textarea_Longitude, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_MainMenu_Textarea_Longitude, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MainMenu_Textarea_Longitude, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_MainMenu_Textarea_Longitude, lv_color_hex(0x000000),
                                  LV_PART_CURSOR | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_MainMenu_Textarea_Longitude, 255, LV_PART_CURSOR | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_MainMenu_Textarea_Longitude, 1, LV_PART_CURSOR | LV_STATE_FOCUSED);
    lv_obj_set_style_border_side(ui_MainMenu_Textarea_Longitude, LV_BORDER_SIDE_LEFT, LV_PART_CURSOR | LV_STATE_FOCUSED);

    lv_obj_set_style_text_color(ui_MainMenu_Textarea_Longitude, lv_color_hex(0x555555),
                                LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MainMenu_Textarea_Longitude, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_MainMenu_Image_timezone = lv_img_create(ui_MainMenu_Tabpage_region);
    lv_img_set_src(ui_MainMenu_Image_timezone, &ui_img_images_timezone_png);
    lv_obj_set_width(ui_MainMenu_Image_timezone, LV_SIZE_CONTENT);   /// 96
    lv_obj_set_height(ui_MainMenu_Image_timezone, LV_SIZE_CONTENT);    /// 96
    lv_obj_set_x(ui_MainMenu_Image_timezone, 24);
    lv_obj_set_y(ui_MainMenu_Image_timezone, 0);
    lv_obj_set_align(ui_MainMenu_Image_timezone, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MainMenu_Image_timezone, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_MainMenu_Image_timezone, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MainMenu_Roller_Hour = lv_roller_create(ui_MainMenu_Tabpage_region);
    lv_roller_set_options(ui_MainMenu_Roller_Hour,
                          "+14\n+13\n+12\n+11\n+10\n+9\n+8\n+7\n+6\n+5\n+4\n+3\n+2\n+1\n0\n-1\n-2\n-3\n-4\n-5\n-6\n-7\n-8\n-9\n-10\n-11\n-12",
                          LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_MainMenu_Roller_Hour, 14, LV_ANIM_OFF);
    lv_obj_set_width(ui_MainMenu_Roller_Hour, 50);
    lv_obj_set_height(ui_MainMenu_Roller_Hour, 100);
    lv_obj_set_x(ui_MainMenu_Roller_Hour, -180);
    lv_obj_set_y(ui_MainMenu_Roller_Hour, 10);
    lv_obj_set_align(ui_MainMenu_Roller_Hour, LV_ALIGN_RIGHT_MID);

    ui_MainMenu_Roller_Minute = lv_roller_create(ui_MainMenu_Tabpage_region);
    lv_roller_set_options(ui_MainMenu_Roller_Minute, "+45\n+30\n+15\n0\n-15\n-30\n-45", LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_MainMenu_Roller_Minute, 3, LV_ANIM_OFF);
    lv_obj_set_width(ui_MainMenu_Roller_Minute, 50);
    lv_obj_set_height(ui_MainMenu_Roller_Minute, 100);
    lv_obj_set_x(ui_MainMenu_Roller_Minute, -110);
    lv_obj_set_y(ui_MainMenu_Roller_Minute, 10);
    lv_obj_set_align(ui_MainMenu_Roller_Minute, LV_ALIGN_RIGHT_MID);

    ui_MainMenu_Roller_Unit = lv_roller_create(ui_MainMenu_Tabpage_region);
    lv_roller_set_options(ui_MainMenu_Roller_Unit, "°C\n°F", LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_MainMenu_Roller_Unit, 3, LV_ANIM_OFF);
    lv_obj_set_width(ui_MainMenu_Roller_Unit, 50);
    lv_obj_set_height(ui_MainMenu_Roller_Unit, 100);
    lv_obj_set_x(ui_MainMenu_Roller_Unit, -40);
    lv_obj_set_y(ui_MainMenu_Roller_Unit, 10);
    lv_obj_set_align(ui_MainMenu_Roller_Unit, LV_ALIGN_RIGHT_MID);

    ui_MainMenu_Label_Label25 = lv_label_create(ui_MainMenu_Tabpage_region);
    lv_obj_set_width(ui_MainMenu_Label_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainMenu_Label_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainMenu_Label_Label25, -49);
    lv_obj_set_y(ui_MainMenu_Label_Label25, -17);
    lv_obj_set_align(ui_MainMenu_Label_Label25, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_MainMenu_Label_Label25, "UTC Offset :Hour   Minute   Unit");
    lv_obj_set_style_text_align(ui_MainMenu_Label_Label25, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainMenu_Tabpage_guide = lv_tabview_add_tab(ui_MainMenu_Tabview_ConfigPanel, "User Guide");
    lv_obj_set_scrollbar_mode(ui_MainMenu_Tabpage_guide, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_MainMenu_Tabpage_guide, LV_DIR_VER);

    ui_MainMenu_Textarea_UserGuide = lv_textarea_create(ui_MainMenu_Tabpage_guide);
    lv_obj_set_width(ui_MainMenu_Textarea_UserGuide, 640);
    lv_obj_set_height(ui_MainMenu_Textarea_UserGuide, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainMenu_Textarea_UserGuide, 0);
    lv_obj_set_y(ui_MainMenu_Textarea_UserGuide, -17);
    lv_obj_set_align(ui_MainMenu_Textarea_UserGuide, LV_ALIGN_TOP_MID);
    lv_textarea_set_text(ui_MainMenu_Textarea_UserGuide,
                         "[Wi-Fi ] - Automatic Connection Setup\n\nSet up your device to automatically connect to your preferred Wi-Fi networks (up to 10 SSIDs).\n- Tap SCAN to search for nearby networks.\n- Select the network you wish to connect to from the dropdown list.\n- Enter the network password.\n- Tap SAVE to save the password\n- Please wait a moment, device is automatically connect to the network.\n\n[ Screen ] - Display Settings\n\nAdjust the behavior of your device's screen.\n- Set Screen Brightness: Adjust the display intensity.\n- Set Screen Off Timer: Control how long the screen stays on after inactivity.\n- Setting the timer to 0 means the screen will always stay on.\n\n[ Radio ] - Custom Radio Station List\n\nYou can create and upload a custom list of radio stations.\n- Create your own stations list using the CSV format in a file named stations.csv (title,url http only)\n- Save the stations.csv file onto your SD Card.\n- Tap UPLOAD to load your custom station list.\n- If the stations.csv file is not available, the device will use the default station list.\n\n[ Music ] - Update Music Library\n\nLoad audio files from your SD Card to create your music library.\n- Supported audio formats include: mp3, flac, aac, and ogg.\n- Copy your audio files to the SD Card. Files can be placed in the root directory or in subfolders (up to 5 levels deep).\n- Tap LOAD to build the music library.\n* Note: This process may take some time, depending on the number of audio files on the SD Card.\n\n[ Region ] - Set weather & clock region\n\n* Auto by IP - the location will be automatically detected by IP\n* Manual -  enter specific Latitude / Longitude\n* UTC offset - set timezone offset\n* Temp - set weather unit Celcius / Farenheit\n\n[ Button Control ]\n\n           [ RESET    ] -  Reset TuneBar\n\n           [ POWER ] - Hold a sec to turn on/ hold 3 sec to turn off\n\n           [  LIGHT  ] - Toggle screen ON/OFF");
    lv_obj_add_flag(ui_MainMenu_Textarea_UserGuide, LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_set_scroll_dir(ui_MainMenu_Textarea_UserGuide, LV_DIR_VER);
    lv_obj_set_style_text_color(ui_MainMenu_Textarea_UserGuide, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MainMenu_Textarea_UserGuide, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainMenu_Textarea_UserGuide, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainMenu_Textarea_UserGuide, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainMenu_Image_buttons = lv_img_create(ui_MainMenu_Textarea_UserGuide);
    lv_img_set_src(ui_MainMenu_Image_buttons, &ui_img_images_button_png);
    lv_obj_set_width(ui_MainMenu_Image_buttons, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainMenu_Image_buttons, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainMenu_Image_buttons, 0);
    lv_obj_set_y(ui_MainMenu_Image_buttons, 10);
    lv_obj_set_align(ui_MainMenu_Image_buttons, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_MainMenu_Image_buttons, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_MainMenu_Image_buttons, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MainMenu_Button_closeConfig = lv_btn_create(ui_Screen_Settings);
    lv_obj_set_width(ui_MainMenu_Button_closeConfig, 50);
    lv_obj_set_height(ui_MainMenu_Button_closeConfig, 50);
    lv_obj_set_align(ui_MainMenu_Button_closeConfig, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_MainMenu_Button_closeConfig, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MainMenu_Button_closeConfig, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainMenu_Button_closeConfig, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainMenu_Button_closeConfig, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MainMenu_Button_closeConfig, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MainMenu_Button_closeConfig, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MainMenu_Button_closeConfig, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainMenu_Label_Label9 = lv_label_create(ui_MainMenu_Button_closeConfig);
    lv_obj_set_width(ui_MainMenu_Label_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainMenu_Label_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MainMenu_Label_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MainMenu_Label_Label9, "X");
    lv_obj_set_style_text_font(ui_MainMenu_Label_Label9, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainMenu_Keyboard_Keyboard1 = lv_keyboard_create(ui_Screen_Settings);
    lv_obj_set_width(ui_MainMenu_Keyboard_Keyboard1, 350);
    lv_obj_set_height(ui_MainMenu_Keyboard_Keyboard1, lv_pct(100));
    lv_obj_set_align(ui_MainMenu_Keyboard_Keyboard1, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_MainMenu_Keyboard_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_MainMenu_Keyboard_Keyboard1, lv_color_hex(0x117200), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainMenu_Keyboard_Keyboard1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_MainMenu_Keyboard_Keyboard1, lv_color_hex(0x143201), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_MainMenu_Keyboard_Keyboard1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainMenu_Keyboard_Number = lv_keyboard_create(ui_Screen_Settings);
    lv_keyboard_set_mode(ui_MainMenu_Keyboard_Number, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_MainMenu_Keyboard_Number, 300);
    lv_obj_set_height(ui_MainMenu_Keyboard_Number, 172);
    lv_obj_set_align(ui_MainMenu_Keyboard_Number, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_MainMenu_Keyboard_Number, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_MainMenu_Keyboard_Number, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainMenu_Keyboard_Number, lv_color_hex(0x0440FC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainMenu_Keyboard_Number, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_MainMenu_Keyboard_Number, lv_color_hex(0x05037F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_MainMenu_Keyboard_Number, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainMenu_Panel_blindPanel = lv_obj_create(ui_Screen_Settings);
    lv_obj_set_width(ui_MainMenu_Panel_blindPanel, lv_pct(100));
    lv_obj_set_height(ui_MainMenu_Panel_blindPanel, lv_pct(100));
    lv_obj_set_x(ui_MainMenu_Panel_blindPanel, -2);
    lv_obj_set_y(ui_MainMenu_Panel_blindPanel, 0);
    lv_obj_set_align(ui_MainMenu_Panel_blindPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MainMenu_Panel_blindPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_MainMenu_Panel_blindPanel,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_MainMenu_Panel_blindPanel, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_MainMenu_Panel_blindPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainMenu_Panel_blindPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainMenu_Panel_blindPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MainMenu_Panel_blindPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MainMenu_Panel_blindPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_add_event_cb(ui_MainMenu_Textarea_Password, ui_event_MainMenu_Textarea_Password, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainMenu_Button_NetworkSave, ui_event_MainMenu_Button_NetworkSave, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainMenu_Button_NetworkScan, ui_event_MainMenu_Button_NetworkScan, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainMenu_Switch_Wifi, ui_event_MainMenu_Switch_Wifi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainMenu_Tabpage_network, ui_event_MainMenu_Tabpage_network, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainMenu_Dropdown_Brightness, ui_event_MainMenu_Dropdown_Brightness, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainMenu_Dropdown_SleepTimer, ui_event_MainMenu_Dropdown_SleepTimer, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainMenu_Dropdown_Wallpaper, ui_event_MainMenu_Dropdown_Wallpaper, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainMenu_Tabpage_screen, ui_event_MainMenu_Tabpage_screen, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainMenu_Button_LoadStation, ui_event_MainMenu_Button_LoadStation, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainMenu_Tabpage_station, ui_event_MainMenu_Tabpage_station, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainMenu_Button_scanMusic, ui_event_MainMenu_Button_scanMusic, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainMenu_Tabpage_music, ui_event_MainMenu_Tabpage_music, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainMenu_Checkbox_AutoIP, ui_event_MainMenu_Checkbox_AutoIP, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainMenu_Textarea_Latitude, ui_event_MainMenu_Textarea_Latitude, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainMenu_Textarea_Longitude, ui_event_MainMenu_Textarea_Longitude, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainMenu_Roller_Hour, ui_event_MainMenu_Roller_Hour, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainMenu_Roller_Minute, ui_event_MainMenu_Roller_Minute, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainMenu_Roller_Unit, ui_event_MainMenu_Roller_Unit, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainMenu_Tabpage_region, ui_event_MainMenu_Tabpage_region, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainMenu_Textarea_UserGuide, ui_event_MainMenu_Textarea_UserGuide, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainMenu_Tabpage_guide, ui_event_MainMenu_Tabpage_guide, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainMenu_Tabview_ConfigPanel, ui_event_MainMenu_Tabview_ConfigPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainMenu_Button_closeConfig, ui_event_MainMenu_Button_closeConfig, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_MainMenu_Keyboard_Keyboard1, ui_MainMenu_Textarea_Password);
    lv_obj_add_event_cb(ui_MainMenu_Keyboard_Keyboard1, ui_event_MainMenu_Keyboard_Keyboard1, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_MainMenu_Keyboard_Number, ui_MainMenu_Textarea_Latitude);
    lv_obj_add_event_cb(ui_MainMenu_Keyboard_Number, ui_event_MainMenu_Keyboard_Number, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainMenu_Panel_blindPanel, ui_event_MainMenu_Panel_blindPanel, LV_EVENT_ALL, NULL);

    // NAS Tab 事件注册
    lv_obj_add_event_cb(ui_MainMenu_Tabpage_nas, ui_event_MainMenu_Tabpage_nas, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainMenu_Dropdown_NasType, ui_event_MainMenu_Dropdown_NasType, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainMenu_Switch_NasHttps, ui_event_MainMenu_Switch_NasHttps, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainMenu_Button_NasSave, ui_event_MainMenu_Button_NasSave, LV_EVENT_ALL, NULL);

    // 注册手势事件回调 - 下边缘上滑返回 Overview
    // 同时注册到整个屏幕和 tabview，确保手势能正确响应
    lv_obj_add_event_cb(ui_Screen_Settings, ui_event_Screen_Settings_gesture, LV_EVENT_GESTURE, NULL);
    lv_obj_add_event_cb(ui_MainMenu_Tabview_ConfigPanel, ui_event_Screen_Settings_gesture, LV_EVENT_GESTURE, NULL);

}

void ui_Screen_Settings_screen_destroy(void)
{
    if(ui_Screen_Settings) lv_obj_del(ui_Screen_Settings);

    // NULL screen variables
    ui_Screen_Settings = NULL;
    ui_MainMenu_Tabview_ConfigPanel = NULL;
    ui_MainMenu_Tabpage_network = NULL;
    ui_MainMenu_Label_connectStatus = NULL;
    ui_MainMenu_Label_Label3 = NULL;
    ui_MainMenu_Dropdown_NetworkList = NULL;
    ui_MainMenu_Textarea_Password = NULL;
    ui_MainMenu_Button_NetworkSave = NULL;
    ui_MainMenu_Label_Label12 = NULL;
    ui_MainMenu_Button_NetworkScan = NULL;
    ui_MainMenu_Label_Label13 = NULL;
    ui_MainMenu_Switch_Wifi = NULL;
    ui_MainMenu_Tabpage_screen = NULL;
    ui_MainMenu_Dropdown_Brightness = NULL;
    ui_MainMenu_Dropdown_SleepTimer = NULL;
    ui_MainMenu_Dropdown_Wallpaper = NULL;
    ui_MainMenu_Label_Label8 = NULL;
    ui_MainMenu_Tabpage_station = NULL;
    ui_MainMenu_Textarea_stationList = NULL;
    ui_MainMenu_Label_Label10 = NULL;
    ui_MainMenu_Button_LoadStation = NULL;
    ui_MainMenu_Label_Label20 = NULL;
    ui_MainMenu_Tabpage_music = NULL;
    ui_MainMenu_Button_scanMusic = NULL;
    ui_MainMenu_Label_Label14 = NULL;
    ui_MainMenu_Label_Label15 = NULL;
    ui_MainMenu_Label_trackCount = NULL;
    ui_MainMenu_Tabpage_region = NULL;
    ui_MainMenu_Image_Globe = NULL;
    ui_MainMenu_Checkbox_AutoIP = NULL;
    ui_MainMenu_Textarea_Latitude = NULL;
    ui_MainMenu_Textarea_Longitude = NULL;
    ui_MainMenu_Image_timezone = NULL;
    ui_MainMenu_Roller_Hour = NULL;
    ui_MainMenu_Roller_Minute = NULL;
    ui_MainMenu_Roller_Unit = NULL;
    ui_MainMenu_Label_Label25 = NULL;
    ui_MainMenu_Tabpage_guide = NULL;
    ui_MainMenu_Textarea_UserGuide = NULL;
    ui_MainMenu_Image_buttons = NULL;
    ui_MainMenu_Button_closeConfig = NULL;
    ui_MainMenu_Label_Label9 = NULL;
    ui_MainMenu_Keyboard_Keyboard1 = NULL;
    ui_MainMenu_Keyboard_Number = NULL;
    ui_MainMenu_Panel_blindPanel = NULL;

    // NAS Tab 变量销毁
    ui_MainMenu_Tabpage_nas = NULL;
    ui_MainMenu_Dropdown_NasType = NULL;
    ui_MainMenu_Textarea_NasIP = NULL;
    ui_MainMenu_Textarea_NasPort = NULL;
    ui_MainMenu_Textarea_NasUser = NULL;
    ui_MainMenu_Textarea_NasPass = NULL;
    ui_MainMenu_Switch_NasHttps = NULL;
    ui_MainMenu_Panel_NasAuth = NULL;
    ui_MainMenu_Label_NasStatus = NULL;
    ui_MainMenu_Button_NasSave = NULL;
    ui_MainMenu_Panel_NasExtra = NULL;
    ui_MainMenu_Textarea_NasExtra1 = NULL;
    ui_MainMenu_Textarea_NasExtra2 = NULL;

    // 存储配置
    ui_MainMenu_Dropdown_SataCount = NULL;
    ui_MainMenu_Dropdown_M2Count = NULL;

}
