// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: tune_bar

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

// Screen event handlers
void ui_Screen_Boot_event_handler(lv_event_t* e);
void ui_Screen_Overview_event_handler(lv_event_t* e);
void ui_event_Screen_Overview_hdd_clicked(lv_event_t* e);

// UI event callbacks
void appStart(lv_event_t * e);
void resetScreenOffTimer(lv_event_t * e);
void informationMode(lv_event_t * e);
void utilityMode(lv_event_t * e);
void saveWiFiCredential(lv_event_t * e);
void scanNetwork(lv_event_t * e);
void toggleWiFi(lv_event_t * e);
void setBrightness(lv_event_t * e);
void setTimer(lv_event_t * e);
void setWallpaper(lv_event_t * e);
void loadStationFromSDCARD(lv_event_t * e);
void loadMusicFromSDCARD(lv_event_t * e);
void set_query_para_autoip(lv_event_t * e);
void setOffsetHour(lv_event_t * e);
void setOffsetMinute(lv_event_t * e);
void setTempUnit(lv_event_t * e);
void saveConfig(lv_event_t * e);
void readKeyboard(lv_event_t * e);
void readNumpad(lv_event_t * e);
void turnonScreen(lv_event_t * e);
void stopWeatherAnimation(lv_event_t * e);
void changeInfoPanelNext(lv_event_t * e);
void changeInfoPanelPrev(lv_event_t * e);
void showArrow(lv_event_t * e);
void updateAQIwidget(lv_event_t * e);
void torch_ON(lv_event_t * e);
void showSystemInfo(lv_event_t * e);
void torch_OFF(lv_event_t * e);
void ota_update(lv_event_t * e);
void ui_event_Screen_Overview_gesture(lv_event_t * e);
void ui_event_Screen_Settings_gesture(lv_event_t * e);
void ui_event_Screen_Storage_gesture(lv_event_t * e);

#ifdef __cplusplus
}
#endif

#endif
